name: Update JSON files
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: python3 gsmarena.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "xiaomifirmwareupdater@gmail.com"
        git config --local user.name "XiaomiFirmwareUpdater"
        git add devices.json all/*.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync: $(date +%d.%m.%Y) [skip ci]"
        git push origin HEAD